name: K6 Load Testing

on:
  push:
    branches: [grafana-results-cloud]

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: scripts/smoke.js
      - name: Send results to K6 Cloud
        run: k6 cloud 792228 --project-id 3640740 --token ${{ secrets.K6_CLOUD_API_TOKEN }}