name: Main Workflow - Cloud
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: script/smoke.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}